version: 2.1
orbs:
  # https://circleci.com/orbs/registry/orb/iynere/compare-url
  compare-url: iynere/compare-url@volatile
jobs:
  docker_build:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.4
    steps:
      - checkout
      - compare-url/reconstruct
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: |
            ./docker/build_docker.sh
workflows:
  version: 2
  full_build:
    jobs:
      - docker_build