name: Docker Available
on: status
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        if: (github.event.context == 'ci/circleci: docker_build' && github.event.state == 'success')
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
