name: Docker Available
on: status
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        if: endsWith(github.event.context, 'docker_build') && github.event.state == 'success'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
